version: "3.7"

services:
  php:
    volumes:
    - ./:/app
    image: composer:2.0

  install:
    volumes:
    - ./:/app
    image: composer:2.0
    command: composer install

  phpunit:
    volumes:
    - ./:/app
    image: composer:2.0
    command: composer phpunit

  test:
    volumes:
    - ./:/app
    image: composer:2.0
    command: composer run tests

  fixcs:
    volumes:
    - ./:/app
    image: composer:2.0
    command: composer run fix-cs
